__version__      = '0.4.0.dev1'
__author__       = 'John Thorvald Wodder II'
__author_email__ = 'daemail@varonathe.org'
__license__      = 'MIT'
__url__          = 'https://github.com/jwodder/daemail'
